### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by rr-** [tarruda/python-fclist#3]
```console
rr-@tornado:~$ pip install --user fclist
Collecting fclist
  Using cached fclist-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/fclist.egg-info
    writing pip-egg-info/fclist.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oo0jcpb8/fclist/setup.py", line 21, in <module>
        zip_safe=False)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/rr-/.local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 273, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/home/rr-/.local/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 609, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib/python3.6/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/home/rr-/.local/lib/python3.6/site-packages/setuptools/dist.py", line 68, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/lib/python3.6/distutils/util.py", line 474, in rfc822_escape
        lines = header.split('\n')
    AttributeError: 'tuple' object has no attribute 'split'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oo0jcpb8/fclist/
rr-@tornado:~$ python -V
Python 3.6.4
```

I suspect the fix is as easy as removing the `,` here: https://github.com/tarruda/python-fclist/blob/master/setup.py#L4

**Comment by MonsieurV** [comment]
Same here!

@tarruda would you accept and publish the fix if we provide the PR?

**Comment by MonsieurV** [comment]
Hi,

I just published the forked I maintain to Pypi: https://pypi.org/project/fclist-cffi/
